In [1]:
import pandas as pd

In [2]:
columns = ["Sex", "Length", "Diameter", "Height", "Whole_weight",
               "Shucked_weight", "Viscera_weight", "Shell_weight", "Rings"]

In [3]:
path = "data/trial_env/data"
path_prepared = f"{path}/prepared_data"

In [4]:
# load main dataset
data = pd.read_csv(f"{path}/abalone.csv", names=columns)
data

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,3,0.400,0.305,0.100,0.3415,0.1760,0.0625,0.0865,7
1,2,0.635,0.500,0.150,1.3760,0.6495,0.3610,0.3100,10
2,3,0.370,0.270,0.090,0.1855,0.0700,0.0425,0.0650,7
3,1,0.680,0.540,0.155,1.5340,0.6710,0.3790,0.3840,10
4,3,0.375,0.285,0.090,0.2545,0.1190,0.0595,0.0675,6
...,...,...,...,...,...,...,...,...,...
4172,3,0.365,0.270,0.085,0.1970,0.0815,0.0325,0.0650,6
4173,3,0.555,0.430,0.140,0.7665,0.3410,0.1650,0.2300,9
4174,3,0.485,0.380,0.120,0.4725,0.2075,0.1075,0.1470,6
4175,2,0.550,0.450,0.145,0.7410,0.2950,0.1435,0.2665,10
4176,3,0.530,0.415,0.145,0.9440,0.3845,0.1850,0.2650,21

In [5]:
# set the last 600 rows to make the reserve dataset
reserved_data = data.iloc[-600:, :]
reserved_data

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
3577,3,0.440,0.320,0.105,0.3875,0.1755,0.0740,0.1200,9
3578,3,0.500,0.380,0.135,0.5940,0.2945,0.1040,0.1565,9
3579,1,0.350,0.260,0.090,0.1950,0.0745,0.0410,0.0655,9
3580,1,0.535,0.430,0.140,0.7165,0.2855,0.1595,0.2155,8
3581,1,0.705,0.560,0.220,1.9810,0.8175,0.3085,0.7600,14
...,...,...,...,...,...,...,...,...,...
4172,3,0.365,0.270,0.085,0.1970,0.0815,0.0325,0.0650,6
4173,3,0.555,0.430,0.140,0.7665,0.3410,0.1650,0.2300,9
4174,3,0.485,0.380,0.120,0.4725,0.2075,0.1075,0.1470,6
4175,2,0.550,0.450,0.145,0.7410,0.2950,0.1435,0.2665,10
4176,3,0.530,0.415,0.145,0.9440,0.3845,0.1850,0.2650,21

In [6]:
# Take out the last 600 rows: This will be used to build the model.
df = data.drop(reserved_data.index)
df

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,3,0.400,0.305,0.100,0.3415,0.1760,0.0625,0.0865,7
1,2,0.635,0.500,0.150,1.3760,0.6495,0.3610,0.3100,10
2,3,0.370,0.270,0.090,0.1855,0.0700,0.0425,0.0650,7
3,1,0.680,0.540,0.155,1.5340,0.6710,0.3790,0.3840,10
4,3,0.375,0.285,0.090,0.2545,0.1190,0.0595,0.0675,6
...,...,...,...,...,...,...,...,...,...
3572,3,0.495,0.355,0.120,0.4965,0.2140,0.1045,0.1495,8
3573,2,0.515,0.375,0.110,0.6065,0.3005,0.1310,0.1500,6
3574,1,0.415,0.315,0.120,0.4015,0.1990,0.0870,0.0970,8
3575,3,0.540,0.435,0.145,0.9700,0.4285,0.2200,0.2640,17
3576,3,0.370,0.280,0.100,0.2210,0.1165,0.0265,0.0635,6

In [7]:
# Save the training reserve and dataset to csv files
df.to_csv(f"{path_prepared}/abalone_data.csv", index=False)  # , index=False

reserved_data.to_csv(f"{path_prepared}/reserved_data.csv", index=False)

In [8]:
df_iter = pd.read_csv(f"{path_prepared}/reserved_data.csv", iterator=True, chunksize=50)

n = 1


while True:
    try:
        df = next(df_iter)
        df.to_csv(f"{path_prepared}/reserved_{n}.csv", index=False)
        print(f"length of reserved_{n}.csv: {len(df)}")
        n += 1
    except StopIteration:
        print("Finished saving data to csv files")
        break

length of reserved_1.csv: 50
length of reserved_2.csv: 50
length of reserved_3.csv: 50
length of reserved_4.csv: 50
length of reserved_5.csv: 50
length of reserved_6.csv: 50
length of reserved_7.csv: 50
length of reserved_8.csv: 50
length of reserved_9.csv: 50
length of reserved_10.csv: 50
length of reserved_11.csv: 50
length of reserved_12.csv: 50
Finished saving data to csv files